# Generated by Django 3.2 on 2022-09-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='baslik'),
        ),
    ]
